### ISSUE TITLE
Incomplete OUTCAR parsing improvements

### ISSUE THREAD

**Issue by ondracka** [nomad-coe/nomad-parser-vasp#10]
The incomplete OUTCAR (usually when the calculation exceeds the scheduled time limits and is killed) handling could use some improvements. The attached file [OUTCAR.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6382550/OUTCAR.zip) has a run with over 100scf iteration and I believe there is also enough info to populate the system section, so it would be nice if the parser could still:
- [x] save the system is such cases
- [x] save all the completed scf iterations
- [x] mark the calculation as "bad", i.e., section_run/run_clean_end=false

**Comment by ladinesa** [comment]
For the last point, I only put a warning when there are no parsed calculation because simply putting a tag bad or not clean run is imho is not specific to be of help.

**Comment by ondracka** [comment]
> For the last point, I only put a warning when there are no parsed calculation because simply putting a tag bad or not clean run is imho is not specific to be of help.

My issue is that there is no easy way to tell from the archive if the calculation ended as it should (as the author intended) which the run_clean_end=false could mark IMO. Please note that the parser also doesn't use single_configuration_calculation_converged as far as I can say (or the is_converged field in the single_point workflow).

What I would love to have is some search criterium which would make the search ignore calculations which obviously did not end as authors intended. However maybe I can bring this up as a general nomad bug (to have some gui search button/checkbox "only show successful/converged calculations", ignore "non-converged/non-zero status calculations") or something similar and than we get back to parsers...

**Comment by ladinesa** [comment]
Now I understand, thanks for the clarification. I should add single_configuration_calculation_converged then. I found a bug in the workflow normalizer that prevents this from being evaluated. I will put a fix in the next commit. Do you also need a flag for convergence for geometry optimizations?

**Comment by ondracka** [comment]
Yes please, similar flag for geometry optimizations would be nice as well.

**Comment by ladinesa** [comment]
I already fixed the bug in single point workflow convergence and also added convergence for geometry optimizations. The pipeline is just running now. For the vasp parser, I also added now single_configuration_calculation_converged. Can you confirm if the desired fix is implemented?

**Comment by ondracka** [comment]
> I already fixed the bug in single point workflow convergence and also added convergence for geometry optimizations. The pipeline is just running now. For the vasp parser, I also added now single_configuration_calculation_converged. Can you confirm if the desired fix is implemented?

It doesn't seem to be working here, I don't see single_configuration_calculation_converged in the archive for example for the attached OUTCAR
[OUTCAR.zip](https://github.com/nomad-coe/nomad-parser-vasp/files/6391975/OUTCAR.zip)

**Comment by ladinesa** [comment]
There should be single_configuration_calculation_converged  but singe_point.is_converged is not because I did a mistake in the workflow and at the same time misplaced the scf tolerance value.  I hope this is finally resolved in the latest commit. If not please let me know.

**Comment by markus1978** [comment]
Sorry for jumping in. Just wanted to clarify, that Alvin's fixes are done on the gitlab nomad-FAIR project, and only on the v0.10.4 branch. Right?

**Comment by ladinesa** [comment]
Affirmative.

**Comment by ondracka** [comment]
Last I tested the 0.10.4 branch this morning. I'll rebuild the latest one tomorrow.

**Comment by ondracka** [comment]
I tested right now with latest 0.10.4 and latest VASP parser and while the OUTCAR from comment 7 is working OK and I see both single_configuration_calculation_converged=true and is_converged=true in workflow. I however still don't see single_configuration_calculation_converged=false for the initial incomplete case from the first comment. So there is still no way to tell that the case is "bad" from the archive 

I still believe that using run_clen_end for the case when the vasprun.xml or OUTCAR is incomplete could be a more reliable :-)

**Comment by ladinesa** [comment]
single_configuration_calculation_converged is determined by reading the line

aborting loop because EDIFF is reached

Not finding this though does not necessarily mean though that the calculation was prematurely terminated. It may mean vasp aborted it because the number of scf iterations was reached or something else. I do not know all the possibilities and the corresponding warnings. Anyway, I will add run_clean=False just based on the trailing line.

**Comment by ondracka** [comment]
> single_configuration_calculation_converged is determined by reading the line
> 
> aborting loop because EDIFF is reached
> 
> Not finding this though does not necessarily mean though that the calculation was prematurely terminated. It may mean vasp aborted it because the number of scf iterations was reached or something else. I do not know all the possibilities and the corresponding warnings.

If one does not see "aborting loop because EDIFF is reached", it might make sense to at least check if section_scc/number_of_scf_iterations is the same as section_method/scf_max_iteration and set single_configuration_calculation_converged to false if so. That should cover the most obvious/likely unconverged case.

> Anyway, I will add run_clean=False just based on the trailing line.

Thank you.
